function Hd = getButterworthFilter(freq1, freq2, order)
%BUTTBOISFILTER Returns a discrete-time freq1 object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 23-Nov-2020 21:03:36

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;   % Sampling Frequency

N   = order;  % Order
Fc1 = freq1;  % First Cutoff Frequency
Fc2 = freq2;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
